"""create test cases table

Revision ID: 3bf3ea4e0372
Revises: 85a7d684fc2b
Create Date: 2026-08-13 14:28:48.768193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf3ea4e0372'
down_revision: Union[str, Sequence[str], None] = '85a7d684fc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('actor_identity_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('ownership_relation', sa.String(length=30), nullable=False),
    sa.Column('expected_statuses', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_identity_id'], ['test_identities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'actor_identity_id', 'resource_id', 'test_type', name='uq_test_case_endpoint_actor_resource_type')
    )
    op.create_index(op.f('ix_test_cases_actor_identity_id'), 'test_cases', ['actor_identity_id'], unique=False)
    op.create_index(op.f('ix_test_cases_endpoint_id'), 'test_cases', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_test_cases_resource_id'), 'test_cases', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_resource_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_endpoint_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_actor_identity_id'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
