"""create resources table

Revision ID: 85a7d684fc2b
Revises: b0af0b36bdc7
Create Date: 2026-08-13 14:13:05.155686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a7d684fc2b'
down_revision: Union[str, Sequence[str], None] = 'b0af0b36bdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('owner_identity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['test_identities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'resource_type', 'external_id', name='uq_resource_target_type_external_id')
    )
    op.create_index(op.f('ix_resources_owner_identity_id'), 'resources', ['owner_identity_id'], unique=False)
    op.create_index(op.f('ix_resources_target_id'), 'resources', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_target_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_owner_identity_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
