"""create security reports table

Revision ID: ca4a0c7159a9
Revises: 94ac6af827a5
Create Date: 2026-08-13 17:38:12.443554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4a0c7159a9'
down_revision: Union[str, Sequence[str], None] = '94ac6af827a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('report_format', sa.String(length=20), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'version', name='uq_security_report_finding_version')
    )
    op.create_index(op.f('ix_security_reports_finding_id'), 'security_reports', ['finding_id'], unique=False)
    op.create_index(op.f('ix_security_reports_target_id'), 'security_reports', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_reports_target_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_finding_id'), table_name='security_reports')
    op.drop_table('security_reports')
    # ### end Alembic commands ###
